[package]
name = "classnote-app"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
# local
data = { workspace = true }
helpers = { workspace = true }
